function datastream = AddCorrectedChannels(datastream, ModeSegregation)

global LM;

options = datastream('Options');

options.Use_HC = 0;
if strcmp(datastream('Options').Test_Cell,'EW3') || ~datastream.isKey('HHC_Bag_Dilute')
    if ~strcmp(datastream('Options').Test_Cell,'EW3'), LM.DebugPrint(1,'ALARM: HHC Analyzer not available, using HC Analyzer instead; chemical balance results may be invalid'); end
    options.Use_HC = 1;
    LM.DebugPrint(2,'Using HC Analyzer for Chemical Balance');
else
    LM.DebugPrint(2,'Using HHC Analyzer for Chemical Balance');
end

datastream('Options') = options;

%{
1065.650(c)(1)(i) Applying the initial THC and CH4 contamination readings according to 1065.520(g),
use the same values for both set of calculations. You may also use as measured values in the initial
set of calculations and corrected values in the drift-corrected set of calculations as described in 1065.520(g)(7).

This section of code uses the pre test zero check with the VZS corrections from the Pre-Test zero span procedure as
the initial contamination concentration on all analyzers, the calculations below reflect this.
%}

if datastream.isKey('CH4_Bag_Dilute') && datastream('Options').Part_1065.IsOn
    NMHCChannel = Analyzer_Channel(datastream, 'NMHC_Bag_Dilute', 'Analyzer', 'ppm', 0);
    CH4Channel = Analyzer_Channel(datastream, 'CH4_Bag_Dilute_Corrected', 'Analyzer', 'ppm', 0);
    
    if datastream('Options').Use_HC
        HCChannel = Analyzer_Channel(datastream, 'HC_Bag_Dilute_Corrected', 'Analyzer', 'ppm', 0);
        
        FirstRangeCH4 = min(cell2mat(datastream('CH4_Bag_Dilute').VZS.keys));
        FirstRangeHC = min(cell2mat(datastream('HC_Bag_Dilute').VZS.keys));
        
        HCChannel.Ambient.PreTest = (datastream('HC_Bag_Dilute').Ambient.PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.PostTest = (datastream('HC_Bag_Dilute').Ambient.PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.Average = (HCChannel.Ambient.PreTest+HCChannel.Ambient.PostTest)/2;
        
        HCChannel.Ambient.Part86PreTest = (datastream('HC_Bag_Dilute').Ambient.Part86PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.Part86PostTest = (datastream('HC_Bag_Dilute').Ambient.Part86PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.Part86Average = (HCChannel.Ambient.Part86PreTest+HCChannel.Ambient.Part86PostTest)/2;
        
        HCChannel.Ambient.Part1065PreTest = (datastream('HC_Bag_Dilute').Ambient.Part1065PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.Part1065PostTest = (datastream('HC_Bag_Dilute').Ambient.Part1065PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck);
        HCChannel.Ambient.Part1065Average = (HCChannel.Ambient.Part1065PreTest+HCChannel.Ambient.Part1065PostTest)/2;
        
        if options.Engine_Modal_Amb_Bag_Test
            HCChannel.Ambient.BagRead = datastream('HC_Bag_Dilute').Ambient.BagRead;
        end
        
        HCChannel.StreamingData.Concentration = datastream('HC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck;
        HCChannel.StreamingData.Part86Concentration = datastream('HC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck;
        HCChannel.StreamingData.Part1065Concentration = datastream('HC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck;
        
        CH4Channel.Ambient.PreTest = ((datastream('CH4_Bag_Dilute').Ambient.PreTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HC_Bag_Dilute').Ambient.PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.PostTest = ((datastream('CH4_Bag_Dilute').Ambient.PostTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HC_Bag_Dilute').Ambient.PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Average = (CH4Channel.Ambient.PreTest+CH4Channel.Ambient.PostTest)/2;
        
        CH4Channel.Ambient.Part86PreTest = ((datastream('CH4_Bag_Dilute').Ambient.Part86PreTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HC_Bag_Dilute').Ambient.Part86PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part86PostTest = ((datastream('CH4_Bag_Dilute').Ambient.Part86PostTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HC_Bag_Dilute').Ambient.Part86PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part86Average = (CH4Channel.Ambient.Part86PreTest+CH4Channel.Ambient.Part86PostTest)/2;
        
        CH4Channel.Ambient.Part1065PreTest = ((datastream('CH4_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HC_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part1065PostTest = ((datastream('CH4_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HC_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part1065Average= (CH4Channel.Ambient.Part1065PreTest+CH4Channel.Ambient.Part1065PostTest)/2;
              
        % EDS Added 2/2/2017
        % Initialize Ambient structure to include BagRead data
        if options.Engine_Modal_Amb_Bag_Test
            CH4Channel.Ambient.BagRead.Concentration = -999*ones(1, ModeSegregation.nPhases); 
            CH4Channel.Ambient.BagRead.Range = zeros(1, ModeSegregation.nPhases);
            CH4Channel.Ambient.BagRead.RangeSize = zeros(1, ModeSegregation.nPhases);
            CH4Channel.Ambient.BagRead.Phase = datastream('CH4_Bag_Dilute').Ambient.BagRead.Phase; 
            if (all(datastream('HC_Bag_Dilute').Ambient.BagRead.Concentration ~= -999) && all(datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration ~= -999)) 
                CH4Channel.Ambient.BagRead.Concentration = (datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration - datastream('HC_Bag_Dilute').Ambient.BagRead.Concentration * datastream('Options').RFPF_C2H6) / ...
                    (1 - datastream('Options').RFPF_C2H6 * datastream('Options').RF_CH4);
                CH4Channel.Ambient.BagRead.Concentration = max(CH4Channel.Ambient.BagRead.Concentration, 0);
            end 
        end
        % end EDS addition
        
        CH4Channel.StreamingData.Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.StreamingData.Part86Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.StreamingData.Part1065Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        
        NMHCChannel.Ambient.PreTest = ((datastream('HC_Bag_Dilute').Ambient.PreTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)- ...
            (datastream('CH4_Bag_Dilute').Ambient.PreTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.Ambient.PostTest = ((datastream('HC_Bag_Dilute').Ambient.PostTest-datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)- ...
            (datastream('CH4_Bag_Dilute').Ambient.PostTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Average = (NMHCChannel.Ambient.PreTest+NMHCChannel.Ambient.PostTest)/2;
        
        NMHCChannel.Ambient.Part86PreTest = ((datastream('HC_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part86PostTest = ((datastream('HC_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part86Average = (NMHCChannel.Ambient.Part86PreTest+NMHCChannel.Ambient.Part86PostTest)/2;
        
        NMHCChannel.Ambient.Part1065PreTest = ((datastream('HC_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part1065PostTest = ((datastream('HC_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part1065Average = (NMHCChannel.Ambient.Part1065PreTest+NMHCChannel.Ambient.Part1065PostTest)/2;
        
        % EDS Added 2/2/2017
        % Initialize Ambient structure to include BagRead data
        if options.Engine_Modal_Amb_Bag_Test
            NMHCChannel.Ambient.BagRead.Concentration = -999*ones(1, ModeSegregation.nPhases); 
            NMHCChannel.Ambient.BagRead.Range = zeros(1, ModeSegregation.nPhases);
            NMHCChannel.Ambient.BagRead.RangeSize = zeros(1, ModeSegregation.nPhases);
            NMHCChannel.Ambient.BagRead.Phase = datastream('HC_Bag_Dilute').Ambient.BagRead.Phase; 
            if (all(datastream('HC_Bag_Dilute').Ambient.BagRead.Concentration ~= -999) && all(datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration ~= -999)) 
                NMHCChannel.Ambient.BagRead.Concentration = datastream('HC_Bag_Dilute').Ambient.BagRead.Concentration - datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration * datastream('Options').RF_CH4;
                NMHCChannel.Ambient.BagRead.Concentration = max(NMHCChannel.Ambient.BagRead.Concentration, 0);
            end  
        end
        % end EDS addition
        
        NMHCChannel.StreamingData.Concentration = ((datastream('HC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.StreamingData.Part86Concentration = ((datastream('HC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.StreamingData.Part1065Concentration = ((datastream('HC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HC_Bag_Dilute').VZS(FirstRangeHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);        
            datastream('HC_Bag_Dilute_Corrected') = HCChannel;
    else %Use HHC
        HHCChannel = Analyzer_Channel(datastream, 'HHC_Bag_Dilute_Corrected', 'Analyzer', 'ppm', 0);
        
        FirstRangeCH4 = min(cell2mat(datastream('CH4_Bag_Dilute').VZS.keys));
        FirstRangeHHC = min(cell2mat(datastream('HHC_Bag_Dilute').VZS.keys));
        
        HHCChannel.Ambient.PreTest = (datastream('HHC_Bag_Dilute').Ambient.PreTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.PostTest = (datastream('HHC_Bag_Dilute').Ambient.PostTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.Average = (HHCChannel.Ambient.PreTest+HHCChannel.Ambient.PostTest)/2;
        
        HHCChannel.Ambient.Part86PreTest = (datastream('HHC_Bag_Dilute').Ambient.Part86PreTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.Part86PostTest = (datastream('HHC_Bag_Dilute').Ambient.Part86PostTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.Part86Average = (HHCChannel.Ambient.Part86PreTest+HHCChannel.Ambient.Part86PostTest)/2;
        
        HHCChannel.Ambient.Part1065PreTest = (datastream('HHC_Bag_Dilute').Ambient.Part1065PreTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.Part1065PostTest = (datastream('HHC_Bag_Dilute').Ambient.Part1065PostTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck);
        HHCChannel.Ambient.Part1065Average = (HHCChannel.Ambient.Part1065PreTest+HHCChannel.Ambient.Part1065PostTest)/2;

        % EDS Added 3/1/2017
        % Initialize the ambient structure to be identical to HC_Bag_Dilute.
        if options.Engine_Modal_Amb_Bag_Test, HHCChannel.Ambient.BagRead = datastream('HC_Bag_Dilute').Ambient.BagRead; end
        % end EDS addition
              
        HHCChannel.StreamingData.Concentration = datastream('HHC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck;
        HHCChannel.StreamingData.Part86Concentration = datastream('HHC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck;
        HHCChannel.StreamingData.Part1065Concentration = datastream('HHC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck;

        CH4Channel.Ambient.PreTest = ((datastream('CH4_Bag_Dilute').Ambient.PreTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HHC_Bag_Dilute').Ambient.PreTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.PostTest = ((datastream('CH4_Bag_Dilute').Ambient.PostTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)- ...
            (datastream('HHC_Bag_Dilute').Ambient.PostTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Average = (CH4Channel.Ambient.PreTest+CH4Channel.Ambient.PostTest)/2;
        
        CH4Channel.Ambient.Part86PreTest = ((datastream('CH4_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part86PostTest = ((datastream('CH4_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part86Average = (CH4Channel.Ambient.Part86PreTest+CH4Channel.Ambient.Part86PostTest)/2;
        
        CH4Channel.Ambient.Part1065PreTest = ((datastream('CH4_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part1065PostTest = ((datastream('CH4_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.Ambient.Part1065Average = (CH4Channel.Ambient.Part1065PreTest+CH4Channel.Ambient.Part1065PostTest)/2;
        
        % EDS Added 3/1/2017
        % Initialize Ambient structure to include BagRead data
        if options.Engine_Modal_Amb_Bag_Test
            CH4Channel.Ambient.BagRead.Concentration = -999*ones(1, ModeSegregation.nPhases); 
            CH4Channel.Ambient.BagRead.Range = zeros(1, ModeSegregation.nPhases);
            CH4Channel.Ambient.BagRead.RangeSize = zeros(1, ModeSegregation.nPhases);
            CH4Channel.Ambient.BagRead.Phase = datastream('CH4_Bag_Dilute').Ambient.BagRead.Phase; 
            if (all(datastream('HHC_Bag_Dilute').Ambient.BagRead.Concentration ~= -999) && all(datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration ~= -999)) 
                CH4Channel.Ambient.BagRead.Concentration = (datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration - datastream('HHC_Bag_Dilute').Ambient.BagRead.Concentration * datastream('Options').RFPF_C2H6) / ...
                    (1 - datastream('Options').RFPF_C2H6 * datastream('Options').RF_CH4);
                CH4Channel.Ambient.BagRead.Concentration = max(CH4Channel.Ambient.BagRead.Concentration, 0);
            end  
        end
        % end EDS addition
        
        CH4Channel.StreamingData.Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.StreamingData.Part86Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        CH4Channel.StreamingData.Part1065Concentration = ((datastream('CH4_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)-(datastream('HHC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)*datastream('Options').RFPF_C2H6)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        
        NMHCChannel.Ambient.PreTest = ((datastream('HHC_Bag_Dilute').Ambient.PreTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)- ...
            (datastream('CH4_Bag_Dilute').Ambient.PreTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.Ambient.PostTest = ((datastream('HHC_Bag_Dilute').Ambient.PostTest-datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)- ...
            (datastream('CH4_Bag_Dilute').Ambient.PostTest-datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/ ...
            (1-datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Average = (NMHCChannel.Ambient.PreTest+NMHCChannel.Ambient.PostTest)/2;
        
        NMHCChannel.Ambient.Part86PreTest = ((datastream('HHC_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part86PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part86PostTest = ((datastream('HHC_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part86PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part86Average = (NMHCChannel.Ambient.Part86PreTest+NMHCChannel.Ambient.Part86PostTest)/2;
        
        NMHCChannel.Ambient.Part1065PreTest = ((datastream('HHC_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part1065PreTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part1065PostTest = ((datastream('HHC_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').Ambient.Part1065PostTest- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1-datastream('Options').RFPF_C2H6* ...
            datastream('Options').RF_CH4);
        NMHCChannel.Ambient.Part1065Average = (NMHCChannel.Ambient.Part1065PreTest+NMHCChannel.Ambient.Part1065PostTest)/2;
        
        % EDS Added 3/1/2017
        % Initialize Ambient structure to include BagRead data
        if options.Engine_Modal_Amb_Bag_Test
            NMHCChannel.Ambient.BagRead.Concentration = -999*ones(1, ModeSegregation.nPhases); 
            NMHCChannel.Ambient.BagRead.Range = zeros(1, ModeSegregation.nPhases);
            NMHCChannel.Ambient.BagRead.RangeSize = zeros(1, ModeSegregation.nPhases);
            NMHCChannel.Ambient.BagRead.Phase = datastream('HHC_Bag_Dilute').Ambient.BagRead.Phase; 
            if (all(datastream('HHC_Bag_Dilute').Ambient.BagRead.Concentration ~= -999) && all(datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration ~= -999)) 
                NMHCChannel.Ambient.BagRead.Concentration = datastream('HHC_Bag_Dilute').Ambient.BagRead.Concentration - datastream('CH4_Bag_Dilute').Ambient.BagRead.Concentration * datastream('Options').RF_CH4;
                NMHCChannel.Ambient.BagRead.Concentration = max(NMHCChannel.Ambient.BagRead.Concentration, 0);
            end  
        end
        % end EDS addition   
        
        NMHCChannel.StreamingData.Concentration = ((datastream('HHC_Bag_Dilute').StreamingData.Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.StreamingData.Part86Concentration = ((datastream('HHC_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Part86Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        NMHCChannel.StreamingData.Part1065Concentration = ((datastream('HHC_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('HHC_Bag_Dilute').VZS(FirstRangeHHC).CorrectedPreTestZeroCheck)-(datastream('CH4_Bag_Dilute').StreamingData.Part1065Concentration- ...
            datastream('CH4_Bag_Dilute').VZS(FirstRangeCH4).CorrectedPreTestZeroCheck)*datastream('Options').RF_CH4)/(1- ...
            datastream('Options').RFPF_C2H6*datastream('Options').RF_CH4);
        
        datastream('HHC_Bag_Dilute_Corrected') = HHCChannel;
    end % if datastream('Options').Use_HC
    
    NMHCChannel.Current_Units{2} = 'g';
    
    datastream('NMHC_Bag_Dilute') = NMHCChannel;
    datastream('CH4_Bag_Dilute_Corrected') = CH4Channel;
end

if datastream.isKey('CO2_Bag_Dilute')
    CorrectionFactor = CVSMassCorrectionFactor(datastream('CO2_Bag_Dilute').StreamingData.Part86Concentration, datastream('Q_CVS').StreamingData, ...
        datastream('V_CVS').StreamingData, datastream('V_Bypass').StreamingData, datastream('Options').Fuel.alpha, datastream('Options').Engine_Bench + ...
        datastream('Options').Tailpipe_Bench);

    LM.DebugPrint(2, 'The mean correction factor for bypass flow (Engine and Tailpipe bench sampling) is %d', mean(CorrectionFactor));

    datastream('Q_CVS_C') = Flow_Channel(datastream, 'Q_CVS_C', 'Flow', datastream('Q_CVS').Current_Units, CorrectionFactor.*datastream('Q_CVS').StreamingData, 0);
    if datastream('Options').Part_1065.IsOn
        datastream('Q_CVS_Mol_C') = Flow_Channel(datastream, 'Q_CVS_Mol_C', 'Flow', datastream('Q_CVS_Mol').Current_Units, CorrectionFactor.*datastream('Q_CVS_Mol').StreamingData, 0);
    end
end